# Generated by Django 3.2.7 on 2021-09-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20210913_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='img2.jpg', upload_to='photos'),
        ),
    ]
